site_name: 'GHテストページ'
site_description: 'GitHub Pagesの練習サイトです。'

copyright: 'Copyright (C) 2019'

theme:
  name: 'material'
  language: 'ja'

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: '#'
  - fontawesome_markdown
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.escapeall
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.superfences
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra_css:
  # - "https://use.fontawesome.com/releases/v5.8.1/css/all.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
